### ISSUE TITLE
Crash on android 

### ISSUE THREAD

**Issue by softsan** [EgorBo/Toasts.Forms.Plugin#135]
Hi,
Got following error while using the plugin with Xamarin.forms  on android 

```
Java.Interop.JniEnvironment Only the original thread that created a view hierarchy can touch its views.

  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <e1b25c832f7f4638988eb7db918de030>:0 
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <97fb620c16ec468bbcf8aef38344c395>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0005d] in <97fb620c16ec468bbcf8aef38344c395>:0 
  at Android.App.Activity.AddContentView (Android.Views.View view, Android.Views.ViewGroup+LayoutParams params) [0x00053] in <a3d78b7f180349b4ac14b6d1208a0a3b>:0 
  at Plugin.Toasts.Manager.AddCroutonToView (Plugin.Toasts.Crouton crouton) [0x00058] in <8f0c3f8cf71a4e67a30c965b92e47fee>:0 
  at Plugin.Toasts.Manager.HandleMessage (Android.OS.Message message) [0x00038] in <8f0c3f8cf71a4e67a30c965b92e47fee>:0 
  at Android.OS.Handler.n_HandleMessage_Landroid_os_Message_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_msg) [0x0000f] in <a3d78b7f180349b4ac14b6d1208a0a3b>:0 
  at (wrapper dynamic-method) System.Object:ec1265b3-f51e-4cf5-9a6d-7fa26751a9df (intptr,intptr,intptr)
  --- End of managed Java.Lang.RuntimeException stack trace ---
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7286)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1155)
	at android.view.View.requestLayout(View.java:21922)
	at android.view.View.requestLayout(View.java:21922)
	at android.view.View.requestLayout(View.java:21922)
	at android.view.View.requestLayout(View.java:21922)
	at android.view.View.requestLayout(View.java:21922)
	at android.view.ViewGroup.addView(ViewGroup.java:4744)
	at android.view.ViewGroup.addView(ViewGroup.java:4718)
	at android.support.v7.app.AppCompatDelegateImplV9.addContentView(AppCompatDelegateImplV9.java:309)
	at android.support.v7.app.AppCompatActivity.addContentView(AppCompatActivity.java:155)
	at md52d189d64b7b0ac40b59b56928c06114b.Manager.n_handleMessage(Native Method)
	at md52d189d64b7b0ac40b59b56928c06114b.Manager.handleMessage(Manager.java:37)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)
```

Any suggestion on this?
Thanks.

**Comment by softsan** [comment]
Any updates/thoughts on this?

**Comment by adamped** [comment]
This is with version 2.0.4. This version is no longer supported. However the issue seems to be calling this on a background thread. Try raising the notification with a Device.BeginInvokeOnMainThread.
