### ISSUE TITLE
Android 5 Crashes On Notify 

### ISSUE THREAD

**Issue by armintelker** [EgorBo/Toasts.Forms.Plugin#14]
Hey Egor, 
I have a problem with the Android Toast on Android 5 (LG Nexus 5  5.01).
For Android 4.x devices everything is fine.

Example Code:
```
DependencyService.Get<IToastNotificator>().Notify(
    ToastNotificationType.Success, 
    text, // "Foo"
    description, //"Bar" 
    TimeSpan.FromSeconds(duration) // 1
);
```

```
System.Diagnostics.Debugger.Mono_UnhandledException_internal () in 
System.Diagnostics.Debugger.Mono_UnhandledException (ex={Java.Lang.NullPointerException: Exception of type 'Java.Lang.NullPointerException' was thrown.
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <IL 0x00011, 0x00068>
at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (intptr,intptr,intptr,Android.Runtime.JValue[]) [0x00084] in /Users/builder/data/lanes/monodroid-mlion-monodroid-4.20-series/ba9bbbdd/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:896
at Android.Runtime.JNIEnv.FinishCreateInstance (intptr,intptr,intptr,Android.Runtime.JValue[]) [0x0000b] in /Users/builder/data/lanes/monodroid-mlion-monodroid-4.20-series/ba9bbbdd/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.cs:288
at Java.Lang.String..ctor (string) [0x000fc] in /Users/builder/data/lanes/monodroid-mlion-monodroid-4.20-series/ba9bbbdd/source/monodroid/src/Mono.Android/platforms/android-19/src/generated/Java.Lang.String.cs:464
at Toasts.Forms.Plugin.Droid.Manager.AnnounceForAccessibilityCompat (Android.Content.Context,string) [0x00044] in d:\tohoto\GitHub\Toasts.Forms.Plugin\Toasts.Forms.Plugin.Droid\Manager.cs:277
at Toasts.Forms.Plugin.Droid.Manager/<>c__DisplayClass1.<CallOnGlobalLayout>b__0 () [0x0005a] in d:\tohoto\GitHub\Toasts.Forms.Plugin\Toasts.Forms.Plugin.Droid\Manager.cs:173
at Toasts.Forms.Plugin.Droid.Manager/GlobalLayoutListener.OnGlobalLayout (System.Action) [0x00000] in d:\tohoto\GitHub\Toasts.Forms.Plugin\Toasts.Forms.Plugin.Droid\Manager.cs:293
at Toasts.Forms.Plugin.Droid.Manager.CallOnGlobalLayout (Toasts.Forms.Plugin.Droid.Crouton,Android.Views.View) [0x00026] in d:\tohoto\GitHub\Toasts.Forms.Plugin\Toasts.Forms.Plugin.Droid\Manager.cs:159
at Toasts.Forms.Plugin.Droid.Manager.AddCroutonToView (Toasts.Forms.Plugin.Droid.Crouton) [0x00070] in d:\tohoto\GitHub\Toasts.Forms.Plugin\Toasts.Forms.Plugin.Droid\Manager.cs:151
at Toasts.Forms.Plugin.Droid.Manager.HandleMessage (Android.OS.Message) [0x0003c] in d:\tohoto\GitHub\Toasts.Forms.Plugin\Toasts.Forms.Plugin.Droid\Manager.cs:104
at Android.OS.Handler.n_HandleMessage_Landroid_os_Message_ (intptr,intptr,intptr) [0x00011] in /Users/builder/data/lanes/monodroid-mlion-monodroid-4.20-series/ba9bbbdd/source/monodroid/src/Mono.Android/platforms/android-19/src/generated/Android.OS.Handler.cs:312
at (wrapper dynamic-method) object.2d792a2f-481d-41bb-bab2-5c909adab5b6 (intptr,intptr,intptr) <IL 0x00017, 0x00043>

  --- End of managed exception stack trace ---
java.lang.NullPointerException: Attempt to read from field 'char[] java.lang.String.value' on a null object reference
	at java.lang.String.<init>(String.java:421)
	at toasts.forms.plugin.droid.Manager.n_handleMessage(Native Method)
	at toasts.forms.plugin.droid.Manager.handleMessage(Manager.java:52)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5221)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
}) in 
object.2d792a2f-481d-41bb-bab2-5c909adab5b6 (arg0=0xffffffffb5051240, arg1=0xffffffffbefb52bc, arg2=0xffffffffbefb52c0) in 
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () in 
Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (jobject=0x100b9e, jclass=0x30050e, jmethod=0x707657d8, parms={Android.Runtime.JValue[1]}) in /Users/builder/data/lanes/monodroid-mlion-monodroid-4.20-series/ba9bbbdd/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:896
Android.Runtime.JNIEnv.FinishCreateInstance (instance=0x100b9e, jclass=0x30050e, constructorId=0x707657d8, constructorParameters={Android.Runtime.JValue[1]}) in /Users/builder/data/lanes/monodroid-mlion-monodroid-4.20-series/ba9bbbdd/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.cs:288
Java.Lang.String..ctor (toCopy=(null)) in /Users/builder/data/lanes/monodroid-mlion-monodroid-4.20-series/ba9bbbdd/source/monodroid/src/Mono.Android/platforms/android-19/src/generated/Java.Lang.String.cs:464
Toasts.Forms.Plugin.Droid.Manager.AnnounceForAccessibilityCompat (context={rebuyapp.android.MainActivity@1875637f}, text=(null)) in d:\tohoto\GitHub\Toasts.Forms.Plugin\Toasts.Forms.Plugin.Droid\Manager.cs:277
Toasts.Forms.Plugin.Droid.Manager. () in d:\tohoto\GitHub\Toasts.Forms.Plugin\Toasts.Forms.Plugin.Droid\Manager.cs:173
Toasts.Forms.Plugin.Droid.Manager.GlobalLayoutListener.OnGlobalLayout (action={System.Action}) in d:\tohoto\GitHub\Toasts.Forms.Plugin\Toasts.Forms.Plugin.Droid\Manager.cs:293
Toasts.Forms.Plugin.Droid.Manager.CallOnGlobalLayout (crouton={toasts.forms.plugin.droid.Crouton@2eff453f}, croutonView={android.widget.LinearLayout{2827474 V.E...C. ......ID 0,0-0,0}}) in d:\tohoto\GitHub\Toasts.Forms.Plugin\Toasts.Forms.Plugin.Droid\Manager.cs:159
Toasts.Forms.Plugin.Droid.Manager.AddCroutonToView (crouton={toasts.forms.plugin.droid.Crouton@2eff453f}) in d:\tohoto\GitHub\Toasts.Forms.Plugin\Toasts.Forms.Plugin.Droid\Manager.cs:151
Toasts.Forms.Plugin.Droid.Manager.HandleMessage (message={{ when=-632ms what=12714097 obj=toasts.forms.plugin.droid.Crouton@2eff453f target=toasts.forms.plugin.droid.Manager }}) in d:\tohoto\GitHub\Toasts.Forms.Plugin\Toasts.Forms.Plugin.Droid\Manager.cs:104
Android.OS.Handler.n_HandleMessage_Landroid_os_Message_ (jnienv=0xffffffffb5051240, native__this=0xffffffffbefb52bc, native_msg=0xffffffffbefb52c0) in /Users/builder/data/lanes/monodroid-mlion-monodroid-4.20-series/ba9bbbdd/source/monodroid/src/Mono.Android/platforms/android-19/src/generated/Android.OS.Handler.cs:312
object.2d792a2f-481d-41bb-bab2-5c909adab5b6 (arg0=0xffffffffb5051240, arg1=0xffffffffbefb52bc, arg2=0xffffffffbefb52c0) in 
```

**Comment by EgorBo** [comment]
Can't reproduce it on my nexus 7 with Android 5, but I guess I know why, thanks for the stack!

**Comment by EgorBo** [comment]
I believe I've fixed it (pushed changes). I'll assembly an update to nuget soon (with fixes for ios).
