### ISSUE TITLE
android: Java.Lang.NullPointerException if next notification is shown before previous is hiding

### ISSUE THREAD

**Issue by canab** [EgorBo/Toasts.Forms.Plugin#37]
varsion: 1.0.6.18

I always call `notificator.HideAll()` before showing any notification to dismiss previous one;
On iOS it works OK.
But on Android it does not hide previous and shows a new one on top instead. After last notification is hidden an exception is thrown:

```
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] Java.Lang.NullPointerException: Exception of type 'Java.Lang.NullPointerException' was thrown.
[MonoDroid] at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/builder/data/lanes/1978/f98871a9/source/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:61
[MonoDroid] at Android.Runtime.JNIEnv.CallVoidMethod (intptr,intptr,Android.Runtime.JValue*) [0x00063] in /Users/builder/data/lanes/1978/f98871a9/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:571
[MonoDroid] at Android.Views.View.StartAnimation (Android.Views.Animations.Animation) [0x0005a] in /Users/builder/data/lanes/1978/f98871a9/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Android.Views.View.cs:18992
[MonoDroid] at Toasts.Forms.Plugin.Droid.Manager.RemoveCrouton (Toasts.Forms.Plugin.Droid.Crouton) [0x00016] in c:\Projects\Toasts.Forms.Plugin\Toasts.Forms.Plugin.Droid\Manager.cs:227
[MonoDroid] at Toasts.Forms.Plugin.Droid.Manager.HandleMessage (Android.OS.Message) [0x00044] in c:\Projects\Toasts.Forms.Plugin\Toasts.Forms.Plugin.Droid\Manager.cs:108
[MonoDroid] at Android.OS.Handler.n_HandleMessage_Landroid_os_Message_ (intptr,intptr,intptr) [0x00011] in /Users/builder/data/lanes/1978/f98871a9/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Android.OS.Handler.cs:356
[MonoDroid] at (wrapper dynamic-method) object.faa8fdcb-fad5-40a2-ad29-238ec4e97112 (intptr,intptr,intptr) <IL 0x00017, 0x00027>
[MonoDroid]   --- End of managed exception stack trace ---
[MonoDroid] java.lang.NullPointerException
[MonoDroid] 	at android.view.View.startAnimation(View.java:16790)
[MonoDroid] 	at md5ec11fdb01388465a68addaebc5a82d67.Manager.n_handleMessage(Native Method)
[MonoDroid] 	at md5ec11fdb01388465a68addaebc5a82d67.Manager.handleMessage(Manager.java:52)
[MonoDroid] 	at android.os.Handler.dispatchMessage(Handler.java:102)
[MonoDroid] 	at android.os.Looper.loop(Looper.java:136)
[MonoDroid] 	at android.app.ActivityThread.main(ActivityThread.java:5001)
[MonoDroid] 	at java.lang.reflect.Method.invokeNative(Native Method)
[MonoDroid] 	at java.lang.reflect.Method.invoke(Method.java:515)
[MonoDroid] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
[MonoDroid] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
[MonoDroid] 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by canab** [comment]
It seems that IToastNotificator.HideAll does not work on android.

**Comment by canab** [comment]
It seams that hiding method has not been implemented.
It just clears queue but do nothing with existing views;
```c#
        public void RemoveCroutons()
        {
            _croutonQueue.Clear();
        }
```

**Comment by canab** [comment]
Pull request:
https://github.com/EgorBo/Toasts.Forms.Plugin/pull/38
